name: time_machine
description: Applications where the user forms his portfolio in the past and looks at how it changes on the timeline

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.0
  riverpod: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_riverpod: ^2.3.4
  analytics:
    path: packages/analytics

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/demo_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/demo_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/demo_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/demo_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/demo_icon.png
    - assets/images/
    - assets/icons/
    - assets/data
