// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8oz_iyBmTLyxtObB0QiG6ATKHdf9CUA4',
    appId: '1:793231606892:android:c912d471ca2a13c65d8449',
    messagingSenderId: '793231606892',
    projectId: 'time-machine-sirius',
    storageBucket: 'time-machine-sirius.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgxwZstGbKxMD9c22WkBc_KBnzWJAP7k',
    appId: '1:793231606892:ios:2af5a8520fd8ade65d8449',
    messagingSenderId: '793231606892',
    projectId: 'time-machine-sirius',
    storageBucket: 'time-machine-sirius.appspot.com',
    androidClientId: '793231606892-jmrlgd1a2eolcofht8plhv5jep23oukf.apps.googleusercontent.com',
    iosClientId: '793231606892-8el394ftpugf0sbrm12k91mu9kdj4cb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeMachine',
  );
}
