name: Flutter Workflow

on: [pull_request]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        
        env:
          FINHUB_KEY: ${{ secrets.FINHUB_KEY }}
      
      - name: Create envirnroment variable
        run: echo "$FINHUB_KEY" > .env
        
      - name: Run codegen
        run: sh script_codegen.sh
        
      - name: Testing
        run: flutter test
