name: Flutter Workflow

on: 
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - shell: bash
        env:
          FINHUB_KEY: ${{ secrets.FINHUB_KEY }}
        run: echo "$FINHUB_KEY" > .env  
        
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      
      - name: Run codegen
        run: sh script_codegen.sh
        
      - name: Build apk
        run: flutter build apk
